In [36]:
import numpy as np

In [37]:
arr = np.array([4,3,43,5,61,72,35,73,455,50,63,67])

In [38]:
arr

array([  4,   3,  43,   5,  61,  72,  35,  73, 455,  50,  63,  67])

In [39]:
np.sort(arr)

array([  3,   4,   5,  35,  43,  50,  61,  63,  67,  72,  73, 455])

In [40]:
np.searchsorted(arr,8)

4

In [41]:
arr1= np.array([4,0,43,5,61,72,0,73,45,50,63,67])

In [42]:
np.count_nonzero(arr1)

10

In [43]:
np.where(arr1>23)

(array([ 2,  4,  5,  7,  8,  9, 10, 11], dtype=int64),)

In [44]:
np.extract(arr1>50,arr1)

array([61, 72, 73, 63, 67])

In [45]:

arr1.byteswap()

array([  67108864,          0,  721420288,   83886080, 1023410176,
       1207959552,          0, 1224736768,  754974720,  838860800,
       1056964608, 1124073472])

In [46]:
a=np.copy(arr1)
a

array([ 4,  0, 43,  5, 61, 72,  0, 73, 45, 50, 63, 67])

In [47]:
b=a.view()
b

array([ 4,  0, 43,  5, 61, 72,  0, 73, 45, 50, 63, 67])

In [48]:
b[0]=100
b

array([100,   0,  43,   5,  61,  72,   0,  73,  45,  50,  63,  67])

In [49]:
import numpy.matlib as nm

In [50]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [51]:
nm.ones((3,2))

matrix([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [52]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [53]:
n=np.random.randint(1,10,[3,4])
n

array([[9, 2, 2, 6],
       [8, 7, 9, 6],
       [8, 7, 8, 9]])

In [54]:
np.expand_dims(n,axis=0)

array([[[9, 2, 2, 6],
        [8, 7, 9, 6],
        [8, 7, 8, 9]]])

In [55]:
np.squeeze(arr1)

array([ 4,  0, 43,  5, 61, 72,  0, 73, 45, 50, 63, 67])

In [56]:
np.roll(n,2)

array([[8, 9, 9, 2],
       [2, 6, 8, 7],
       [9, 6, 8, 7]])

In [57]:
np.diag(n)

array([9, 7, 8])

In [58]:
d1=np.random.randint(1,7,(4,4))
d1
d2=np.random.randint(5,10,(4,4))
d2

array([[8, 9, 8, 8],
       [8, 6, 7, 9],
       [9, 6, 7, 5],
       [5, 8, 8, 6]])

In [59]:
d1+d2

array([[10, 11, 12,  9],
       [ 9, 11, 11, 12],
       [15,  8, 12, 11],
       [10, 14, 13,  8]])

In [60]:
d1*d2

array([[16, 18, 32,  8],
       [ 8, 30, 28, 27],
       [54, 12, 35, 30],
       [25, 48, 40, 12]])

In [61]:
d2-d1

array([[ 6,  7,  4,  7],
       [ 7,  1,  3,  6],
       [ 3,  4,  2, -1],
       [ 0,  2,  3,  4]])

In [62]:
d2/d1

array([[4.        , 4.5       , 2.        , 8.        ],
       [8.        , 1.2       , 1.75      , 3.        ],
       [1.5       , 3.        , 1.4       , 0.83333333],
       [1.        , 1.33333333, 1.6       , 3.        ]])

In [63]:
d2%d1

array([[0, 1, 0, 0],
       [0, 1, 3, 0],
       [3, 0, 2, 5],
       [0, 2, 3, 0]])

In [64]:
d1 & d2

array([[0, 0, 0, 0],
       [0, 4, 4, 1],
       [0, 2, 5, 4],
       [5, 0, 0, 2]])

In [65]:
d1>d2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [66]:
#string function

In [67]:
s1=np.array(["saurabh","patil"])

In [68]:
s1.dtype

dtype('<U7')

In [69]:
np.char.upper(s1)

array(['SAURABH', 'PATIL'], dtype='<U7')

In [81]:
n2=np.random.randint(1,7,(4,4))
n2

array([[3, 1, 6, 6],
       [6, 5, 5, 3],
       [5, 4, 2, 5],
       [1, 5, 2, 3]])

In [74]:
np.tan(n2)

array([[ 1.15782128, -2.18503986, -2.18503986,  1.55740772],
       [-3.38051501, -3.38051501, -3.38051501, -2.18503986],
       [-3.38051501, -0.29100619, -3.38051501, -3.38051501],
       [ 1.15782128, -0.29100619,  1.15782128, -0.29100619]])

In [75]:
np.cos(n2)

array([[-0.65364362, -0.41614684, -0.41614684,  0.54030231],
       [ 0.28366219,  0.28366219,  0.28366219, -0.41614684],
       [ 0.28366219,  0.96017029,  0.28366219,  0.28366219],
       [-0.65364362,  0.96017029, -0.65364362,  0.96017029]])

In [76]:
np.mean(n2)

4.1875

In [77]:
np.std(n2)

1.5499495959546556

In [78]:
np.var(n2)

2.40234375

In [80]:
np.min(n2)

1

In [79]:
np.max(n2)

6

In [82]:
np.sqrt(n2)

array([[1.73205081, 1.        , 2.44948974, 2.44948974],
       [2.44948974, 2.23606798, 2.23606798, 1.73205081],
       [2.23606798, 2.        , 1.41421356, 2.23606798],
       [1.        , 2.23606798, 1.41421356, 1.73205081]])

In [83]:
np.exp(n2)

array([[ 20.08553692,   2.71828183, 403.42879349, 403.42879349],
       [403.42879349, 148.4131591 , 148.4131591 ,  20.08553692],
       [148.4131591 ,  54.59815003,   7.3890561 , 148.4131591 ],
       [  2.71828183, 148.4131591 ,   7.3890561 ,  20.08553692]])